### ISSUE TITLE
r = pdf.abstract(chem=True) only possible for abstract?

### ISSUE THREAD

**Issue by ViktorWeissenborn** [cat-lemonade/PDFDataExtractor#1]
Hey,

it seems to me that only the abstract-method can be used right now with chemdataextractor if chem is True. Is there an implemented way to screen the whole pdf text with chemdataextractor?

I can of course just take the plaintext()-method, take the full pdf-text-string and run it manually through chemdataextractor. But as mentioned above, i was wondering if there is an implemented way in PDFDataExtractor to do that.

greetings
viktor

**Comment by cat-lemonade** [comment]
Hi Viktor, 

Sorry for the super delayed reply. So many thanks for your comments but ATM, I am taken by other things, so probably I won't be able to work on the details of the project. For the time being, you can simply use ChemDataExtractor v2.0 to perform CNR as PDFDataExtractor focuses more on metadata extraction.

FYI:
https://cambridgemolecularengineering-chemdataextractor-development.readthedocs-hosted.com/en/latest/introduction/reading_docs.html

Cat
