### ISSUE TITLE
Getting None from file.read_file(path)

### ISSUE THREAD

**Issue by areyoukillingm3** [cat-lemonade/PDFDataExtractor#2]
Hello!  I'm running the following code and getting the error message below:

```
from pdfdataextractor import Reader
path = r'/Users/eightyfour/working/llm-sci/PDFDataExtractor/demo/test.pdf'
file = Reader()
pdf = file.read_file(path)
pdf.test()
```

```
Reading:  /Users/eightyfour/working/llm-sci/PDFDataExtractor/demo/test.pdf
*** Elsevier detected ***
Traceback (most recent call last):
  File "/Users/eightyfour/working/llm-sci/PDFDataExtractor/demo/run.py", line 5, in <module>
    pdf.test()
AttributeError: 'NoneType' object has no attribute 'test'
```

`pdf = file.read_file(path)` takes ~12 seconds and detects Elsevier as you can see, but test always gets None.  `print(pdf)` returns None as well, so that tracks :)  Any tips would be helpful!  

Thanks,

Mark

**Comment by cat-lemonade** [comment]
Dear Mark,

So many thanks for using the PDFDataExtractor,

Would you mind sending me the file you are trying to extract? As I can see from the traceback, you are trying to extract from Elsevier.

All the best,
Miao

On 9 Jul 2023, at 21:26, areyoukillingm3 ***@***.***> wrote:



Hello! I'm running the following code and getting the error message below:

path = r'/Users/eightyfour/working/llm-sci/PDFDataExtractor/demo/test.pdf'
file = Reader()
pdf = file.read_file(path)
pdf.test()```

Reading:  /Users/eightyfour/working/llm-sci/PDFDataExtractor/demo/test.pdf
*** Elsevier detected ***
Traceback (most recent call last):
  File "/Users/eightyfour/working/llm-sci/PDFDataExtractor/demo/run.py", line 5, in <module>
    pdf.test()
AttributeError: 'NoneType' object has no attribute 'test'

`pdf = file.read_file(path)` takes ~12 seconds and detects Elsevier as you can see, but test always gets None.  `print(pdf)` returns None as well, so that tracks :)  Any tips would be helpful!  Thanks,

Mark

**Comment by areyoukillingm3** [comment]
[test.pdf](https://github.com/cat-lemonade/PDFDataExtractor/files/12035270/test.pdf)
oh, great!  here ya go :)

thanks,

mark

**Comment by cat-lemonade** [comment]
Hi Mark,

Many thanks for sharing the file. However, this is a non-standard Elsevier layout that PDFDataExtractor is not able to handle atm. Please refer to the following for a standard Elsevier layout:

https://beta.elsevier.com/editor/article-layout?trial=true

Cat

**Comment by areyoukillingm3** [comment]
Will look into it!  Thanks for the reference :)

**Comment by areyoukillingm3** [comment]
Will look into it! Thanks for the reference :)
