### ISSUE TITLE
Great tool but only able to run with python3.8

### ISSUE THREAD

**Issue by Jgmedina95** [cat-lemonade/PDFDataExtractor#3]
Hi!
Seems like a great package for what I need!

I struggled to install it, and only made it possible with a downgrade to python version 3.8.
The package that created the problem was chemdataextractor.

Is it necessary for the overall code? I'm happy only with text so far, so maybe the package is not completely necessary and ill be able to keep using more recent versions of python

**Comment by Jgmedina95** [comment]
Going into the source code, I found that chemdataextractor is only been used for the abstract(chem=true) case. I can live happily without it haha. It seems that chemdataextractor is not been maintained correctly. As the last closed issue was over 2 years ago. https://github.com/mcs07/ChemDataExtractor/issues?q=is%3Aissue+is%3Aclosed

Maybe the import statement for that functionality can hide inside the if else statement, with the warning of only using it with older python versions.

**Comment by cat-lemonade** [comment]
Hi Jgmedina95,

Many thanks for your comments.

Glad that you found this package helpful, much appreciated. I would suggest the followings: 

i) To create a conda environment with python 3.8, which should be able to help with this issue, and your other environments will not be affected;

ii) ChemDataExtrctor remains a critical component of PDFDataExtractor, so unfortunately I will not be able to remove it, but your suggestions are of great value, which will be reflected in the next version. But I am taken by other things atm, therefore I cannot inform you the timeframe;

iii) Please do feel free to make your very own version of this package :) 

iv) ChemDataExtractor v2.0 is available, please see: https://cambridgemolecularengineering-chemdataextractor-development.readthedocs-hosted.com/en/latest/
