### ISSUE TITLE
Adding to this repo

### ISSUE THREAD

**Issue by EllieDeSota** [cat-lemonade/PDFDataExtractor#5]
Hey! 

I'm working on a project with DeSci labs (desci.com) that is emphasizing generating automatic metadata. And we were hoping to use your repo as a basis for getting metadata from the text itself (including combining the functionality with LLMs and some other tooling). 

Right now, we've just forked your repository and are keeping any changes we make separate. But we wanted to check in to see if you would be interested in us adding any of our changes to your repo to make it more robust. 

Thanks!

**Comment by cat-lemonade** [comment]
Hi,

Thanks for reaching out! and glad that this package works for you. But for now, I have to keep this repo unchanged. 

Many thanks!
